name: Documentation
description: Suggest an improvement or correction to the documentation
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the documentation change.
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Location
      description: Which file or section should be changed?
